### ISSUE TITLE
两个vxe-table好像会一直卡着加载不出来

### ISSUE THREAD

**Issue by allran** [x-extends/vxe-table#2620]
### 可复现的链接（包含复现链接与示例代码）：

1

### 问题描述与截图：

使用el-tabs，分别加了vxe-table表，会卡住。注释掉一个时可以加载。我给两个vxe-table设置不同的ref也不行。

### 操作系统：

mac

### 浏览器版本：

chrome 130.0.6723.91（正式版本） (x86_64)

### vue 版本：

"vue": "^3.5.12",

### vxe-pc-ui 版本：

"vxe-pc-ui": "^4.2.34",

### vxe-table 版本：

"vxe-table": "^4.7.97"

### 是否使用当前最新版本？

- [X] 我已确认是使用当前的最新版本并已按要求提供复现链接与示例代码。

**Comment by lattaai1** [comment]
Hello, I've fixed this issue!

This is what I've done:
To fix the issue of vxe-table not loading when used inside el-tabs, I made the following changes:

1. In the parent component containing el-tabs, I added a v-if directive to the tab panes to conditionally render the vxe-table components only when the tab is active.

2. I also added a key prop to each tab pane to force a re-render when switching tabs.

3. In the child components containing vxe-table, I moved the data loading logic from onMounted to onActivated, so the table data is refreshed each time the tab becomes active.

These changes should allow the vxe-tables to load properly when switching between tabs.

I also created pull request: https://github.com/x-extends/vxe-table/pull/2621


> [!CAUTION]  
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission
